### ISSUE TITLE
Enable automerge for all repos

### ISSUE THREAD

**Issue by bstrie** [enarx/.github#29]
As is done in the `enarx/enarx` repo, all repos in the Enarx organization should have automerge enabled.

**Comment by dpal** [comment]
Went through all the repositories in the Enarx organization and made sure that auto-merge is turned on.
@bstrie is there anything else to be done for this ticket?

**Comment by dpal** [comment]
Make it blocked on shared workflows.

**Comment by dpal** [comment]
Blocked by https://github.com/enarx/.github/issues/30

**Comment by dpal** [comment]
This ticket is now done.
Refs #37 #36
